#!/bin/bash

log=$HOME/.bspwm-errors
kind=run

opt=(
    "VBoxClient-all &"
    "blackwalls &"
    "shotkey &"
    "xbanish &"
    "xcompmgr &"
)

log() {
    echo "[$$.$(date +%N)]$@"
}

spawn() {
    for i in "${opt[@]}"; do
        app=$(echo "$i" | awk '{print $1}')
        if [ -n "$(which $app)" ]; then
            log "[spawn] run $app."
            eval "$i" >/dev/null 2>&1
        fi
    done
}

run() {
    log "[bspwm] start bspwm on run mode."
    log "[bspwm] start applications."
    spawn
    exec bspwm >/dev/null 2>&1
}

debug() {
    log "[bspwm] start bspwm on debug mode."
    log "[bspwm] start applications."
    spawn
    exec bspwm
}

case $kind in
    run|-r )
        run >$log 2>&1
        ;;
    debug|-d )
        debug >$log 2>&1
        ;;
esac
