#!/bin/sh
# Reborn active terminal in its current working directory (or SSH context)

# Default terminal command fallback
TERM_CMD="st"

# Get active window ID (Exit early if no window active)
WIN_ID=$(xprop -root _NET_ACTIVE_WINDOW 2>/dev/null | awk '{print $NF}')
[ -z "$WIN_ID" ] || [ "$WIN_ID" = "0x0" ] && exec $TERM_CMD

# Auto-detect if current window is st or urxvt
WIN_CLASS=$(xprop -id "$WIN_ID" WM_CLASS 2>/dev/null | awk -F '"' '{print tolower($4)}')
case "$WIN_CLASS" in
    urxvt*|rxvt* )
        TERM_CMD="urxvt"
        ;;
    st* )
        TERM_CMD="st"
        ;;
esac

# Extract main PID from window
PID=$(xprop -id "$WIN_ID" _NET_WM_PID 2>/dev/null | awk '{print $NF}')

if echo "$PID" | grep -qE '^[0-9]+$'; then
    # Find leaf child process (shell/running program) in process tree
    CHILD_PID=$(pstree -lpA "$PID" 2>/dev/null | tail -n 1 | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')
    [ -n "$CHILD_PID" ] && PID="$CHILD_PID"

    # Get Current Working Directory (CWD)
    [ -d "/proc/$PID/cwd" ] && PCWD=$(readlink "/proc/$PID/cwd" 2>/dev/null)

    # Check if running SSH command
    if [ -f "/proc/$PID/cmdline" ]; then
        PCMDLINE=$(tr '\0' ' ' < "/proc/$PID/cmdline" 2>/dev/null | sed -e 's/[[:space:]]*$//')
        PCMD=$(echo "$PCMDLINE" | awk '{print $1}')
    fi
fi

# Change script working directory before spawning
if [ -d "$PCWD" ]; then
    cd "$PCWD" || cd "$HOME"
fi

# Spawn new terminal & kill old window
case "$PCMD" in
    ssh|*/ssh )
        case $TERM_CMD in
            st* ) TERM_CMD="$TERM_CMD -x" ;;
        esac
        setsid $TERM_CMD -e $PCMDLINE >/dev/null 2>&1 &
        ;;
    * )
        setsid $TERM_CMD >/dev/null 2>&1 &
        ;;
esac

sleep 0.05
xdotool windowkill "$WIN_ID"
