/*
 * Buffer Menu as per Big Emacs
 * Author: Hugh Barney, hughbarney@gmail.com, March 2013
 *
 * Display the buffer list in a window and operate on it
 * using the following keys:
 *
 * N,n, CTRL+N, down-arrow:   move to next line
 * P,p, CTRL+P, up-arrow:     move to prev line
 * s  save buffer at line
 * v  toggle read only flag
 * k  kill buffer at line
 * 1  select buffer at line
 * 2  select buffer in split window below original window
 * q,Q,x,X exit buffer menu
 *
 */

#include "def.h"

#define ESC 27
#define BACKSPACE 127
#define CTRL_N CCHR('N')
#define CTRL_M CCHR('M')
#define CTRL_P CCHR('P')
#define CTRL_H CCHR('H')

/* Forward declarations */
static BUFFER *get_buffer(int n);
static int valid_buf(BUFFER* bp_try);
static int count_buffers(void);
static int is_visible_buffer(BUFFER *bp);

/*
 * Buffer MENU.
 */
int
buffermenu(int f, int n, int k)
{
  BUFFER *bp;
  BUFFER *org_bp = curbp;
  int c, l;
  int bufptr;
  int bufcount = 0;

  bufptr = 1;

start:
  /* Regenerate active list layout structures cleanly on each pass */
  listbuffers(f, n, KRANDOM);
  if (blistp == NULL) return FALSE;

  swbuffer(blistp);
  onlywind(0, 0, KRANDOM);
  bufcount = count_buffers();

  if (bufptr > bufcount)
    bufptr = bufcount;
  if (bufptr < 1)
    bufptr = 1;

  /* Skip table metadata headers generated by native listbuffers() routing */
  if (bufcount > 0)
    forwline(0, bufptr + 1, KRANDOM);
  else
    forwline(0, 2, KRANDOM);

  for (;;)
    {
      /* ======================================================== */
      /* Old-school minimal prompt                                */
      /* ======================================================== */
      eprintf("Buffer Menu: 1,2,s,v,k,q");
      /* ======================================================== */

      update();
      c = ttgetc();

      /* Lock input context to terminal escape handling sequences if no items remain */
      if (bufcount == 0)
        {
          switch (c)
            {
            case 'q': case 'Q': case 'x': case 'X':
              break;
            default:
              ttbeep();
              continue;
            }
        }

      /* ======================================================== */
      /* DUAL-TRACK KEYBOARD INTERCEPTOR                          */
      /* Track 1: Handle native cooked integer mappings generated */
      /* by active ncurses configurations (258=DOWN, 259=UP).     */
      /* ======================================================== */
      if (c == 258) c = CTRL_N;
      if (c == 259) c = CTRL_P;

      /* ======================================================== */
      /* Track 2: Legacy escape multi-byte stream parsing via     */
      /* getctl(). Retained for vintage TTY terminal engines.     */
      /* ======================================================== */
      if (c == ESC)
        {
          l = getctl();
          if (l == '[')
            {
              l = getctl();
              switch(l)
                {
                case 'A': c = CTRL_P; break; /* Standard ANSI Up Arrow Key */
                case 'B': c = CTRL_N; break; /* Standard ANSI Down Arrow Key */
                default:
                  ttbeep();
                  continue;
                }
            }
          else
            {
              l = getctl();
              ttbeep();
              continue;
            }
        }

      switch (c)
        {
        case 'n':
        case 'N':
        case ' ':
        case CTRL_N:
          if (bufcount <= bufptr)
            {
              ttbeep();
              break;
            }
          forwline(0, 1, KRANDOM);
          bufptr++;
          break;

        case 'p':
        case 'P':
        case CTRL_P:
        case CTRL_H:
        case BACKSPACE:
          if (bufptr <= 1)
            {
              ttbeep();
              break;
            }
          backline(0, 1, KRANDOM);
          bufptr--;
          break;

        case '1':
        case CTRL_M:
          bp = get_buffer(bufptr);
          if (bp == NULL) { ttbeep(); break; }
          swbuffer(bp);
          onlywind(0, 0, KRANDOM);
          eerase();
          sgarbf = TRUE; /* Instruct global engine loop to force hard refresh cycle */
          return TRUE;

        case '2':
          bp = get_buffer(bufptr);
          if (bp == NULL) { ttbeep(); break; }
          swbuffer(bp);
          onlywind(0, 0, KRANDOM);

          /* Validate origin pointer survival state and strip active list cross-linking */
          if (valid_buf(org_bp) == TRUE && bufcount > 1 && org_bp != blistp)
            {
              splitwind(0, 0, KRANDOM);
              swbuffer(org_bp);
              nextwind(0, 0, KRANDOM);
            }
          eerase();
          sgarbf = TRUE;
          return TRUE;

        case 's':
        case 'S':
          bp = get_buffer(bufptr);
          if (bp != NULL && bp != blistp)
            {
              curbp = bp;
              (void)filesave(0, 0, KRANDOM);
              curbp = blistp;
              goto start;
            }
          else {
              ttbeep();
          }
          break;

        case 'v':
        case 'V':
        case '%':
          bp = get_buffer(bufptr);
          if (bp != NULL && bp != blistp)
            bp->b_flag ^= BFRO;
          goto start;

        case 'd':
        case 'D':
        case 'k':
        case 'K':
          bp = get_buffer(bufptr);

          /*
           * Anti-suicide trap: Protect operational list allocation structure.
           * Eradicates wild reference drops across blistp targets.
           */
          if (bp == blistp)
            {
              eprintf("Cannot kill buffer menu container.");
              ttbeep();
              break;
            }

          if (bp != NULL)
            {
              if (eyesno("Kill buffer") == TRUE)
                {
                  zotbuf(bp);

                  /* Nullify context trace tracking maps if calling node is wiped */
                  if (bp == org_bp) org_bp = NULL;

                  /* Reposition indices downward following node reduction bounds */
                  if (bufptr > 1) bufptr--;
                }
            }
          goto start;

        case 'q':
        case 'Q':
        case 'x':
        case 'X':
          if (bufcount == 0)
            {
              bp = getscratch();
              swbuffer(bp);
              onlywind(0, 0, KRANDOM);
              eerase();
              sgarbf = TRUE;
              return TRUE;
            }

          if (valid_buf(org_bp) == TRUE && org_bp != blistp)
            swbuffer(org_bp);
          else
            {
              /* Gracefully sweep nodes to find the next active user matrix workspace */
              bp = bheadp;
              while (bp != NULL && (!is_visible_buffer(bp) || bp == blistp))
                bp = bp->b_bufp;

              if (bp != NULL)
                swbuffer(bp);
              else
                swbuffer(getscratch());
            }
          onlywind(0, 0, KRANDOM);
          eerase();
          sgarbf = TRUE;
          return TRUE;

        default:
          ttbeep();
          break;
        }
    }

  eerase();
  return TRUE;
}

/*
* Calculate targeted visible data rows.
* Maintains structural parity with items rendered to display buffers.
*/
BUFFER*
get_buffer(int n)
{
  BUFFER *bp;
  int i = 0;

  bp = bheadp;
  while (bp != NULL)
    {
      if (is_visible_buffer(bp))
        {
          if (++i == n)
            return bp;
        }
      bp = bp->b_bufp;
    }
  return NULL;
}

/*
 * Enumerate total non-hidden user layout instances
 */
int
count_buffers(void)
{
  BUFFER *bp;
  int count = 0;

  bp = bheadp;
  while (bp != NULL)
    {
      if (is_visible_buffer(bp))
        count++;
      bp = bp->b_bufp;
    }
  return count;
}

int
valid_buf(BUFFER* bp_try)
{
  BUFFER *bp;

  if (bp_try == NULL) return FALSE;
  bp = bheadp;
  while (bp != NULL)
    {
      if (bp == bp_try)
        return TRUE;
      bp = bp->b_bufp;
    }
  return (FALSE);
}

/*
* Filter out anonymous or system-internal buffers.
* Returns FALSE for hidden pools (e.g., space-prefixed names).
*/
int
is_visible_buffer(BUFFER *bp) {
  if (bp == NULL) return FALSE;
  if (bp->b_bname[0] == ' ') return FALSE;
  return TRUE;
}
