#!/bin/bash

title="window:"
lines=10
desktop=$(xdotool get_desktop)
windows=$(wmctrl -xl 2>/dev/null | grep -E "\s+${desktop}\s+")
apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 3-3,5- | \
           sed 's/[a-zA-Z0-9-]*\.//')

# Add spaces to align the WM_NAMEs of the windows
max=$(echo -n "$apps" | awk '{cur=length($1); \
                              max=(cur>max?cur:max)} END{print max}')

apps=$(echo -n "$apps" | \
           awk -v max="$max" \
               '{cur=length($1); \
                 printf $1; \
                 for(i=0; i < max - cur + 1; i++) printf " "; \
                 $1=""; \
                 printf "%s\n", $0}')

target=$(echo -n "$apps" | dmenu -l $lines -i -ix -p $title)

if [ -n "$target" ]; then
    apps=($(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1))
    exec wmctrl -i -a ${apps[$target]}
fi
