#!/bin/bash

title="desktop:"
lines=10

desks() {
    group=$(xdotool get_desktop)
    total=$(wmctrl -lp | awk '{print $2}' | wc -l)
    labels=(one two three four five six seven eight nine)
    case $DESKTOP_SESSION in
        cwm )
            for i in $(seq 0 8); do
                l=${labels[$i]};
                g=$(expr $i + 1);
                n=$(wmctrl -lp | awk '{print $2}' | grep -sc "^${g}$")
                if [ ${group} -eq ${g} ]; then
                    f="*"
                else
                    f="-"
                fi
                printf '%-8s%4s%20s\n' "${l}" "${f}" "${n}/${total}"
            done
            ;;
        dwm )
            for i in $(seq 0 8); do
                l=${labels[$i]};
                n=$(wmctrl -lp | awk '{print $2}' | grep -sc "^${i}$")
                if [ ${group} -eq ${i} ]; then
                    f="*"
                else
                    f="-"
                fi
                printf '%-8s%4s%20s\n' "${l}" "${f}" "${n}/${total}"
            done
            ;;
        * )
            ;;
    esac
}

target=$(desks | dmenu -l $lines -i -ix -p $title)
if [ -n "$target" ]; then
    xdotool key super+$(expr $target + 1)
fi
