#!/bin/bash

[ $# -lt 1 ] && cat <<EOF && exit
Usage: $(basename $0) {app} [cmd]
app   --  app name or class
cmd   --  command string (option)
EOF

app=${1}
cmd=${2:-$app}
title="app:"
lines=10
windows=$(wmctrl -xl 2>/dev/null)
num=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 3 | \
          sed 's/[a-zA-Z0-9-]*\.//' | grep -i "$app" | wc -l)

app_run() {
    hash $cmd 2>/dev/null
    if [ $? -eq 0 ]; then
        exec $cmd
    fi
}

app_menu() {
    apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1-3,5- | \
               sed 's/[a-zA-Z0-9-]*\.//' | grep -i -E "\s+${app}\s+" )
    # Add spaces to align the WM_NAMEs of the windows
    max=$(echo -n "$apps" | awk '{cur=length($3); \
                              max=(cur>max?cur:max)} END{print max}')
    wm=$(wmctrl -m | grep Name: | awk '{print $2}')
    id=$(xdotool getactivewindow)
    apps=$(echo -n "$apps" | \
               awk -v max="$max" \
                   -v wm="$wm" \
                   -v id="$id" \
                   '{cur=length($3);
                     group[0]="one";
                     group[1]="two";
                     group[2]="three";
                     group[3]="four";
                     group[4]="five";
                     group[5]="six";
                     group[6]="seven";
                     group[7]="eight";
                     group[8]="nine";
                     id1=sprintf("%d", $1);
                     id2=sprintf("%d", id);
                     tag=" ";
                     if(wm=="CWM") $2-=1;
                     printf "%-8s", group[$2];
                     if(id1==id2) tag="*";
                     printf "%-2s", tag;
                     printf "%s", $3;
                     for(i=0;i<max-cur+1;i++) printf " ";
                     $1=$2=$3="";
                     printf "%s\n", $0}')
    target=$(echo -n "$apps" | dmenu -l $lines -i -ix -r -p $title)
    case $target in
        '' ) exit ;;
        NEW )
            app_run
            ;;
        * )
            apps=($(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1,3 | \
                       grep -i "[[:space:]]\+$app" | cut -d ' ' -f 1))
            winid=${apps[$target]}
            xdotool windowactivate $winid
            xdotool windowraise $winid
            xdotool windowfocus $winid
            ;;
    esac
}

case $num in
    0 )
        app_run
        ;;
    * )
        app_menu
        ;;
esac
