#!/bin/bash

title="info:"
lines=10
desktop=$(xdotool get_desktop)
windows=$(wmctrl -xl 2>/dev/null | grep -E "\s+${desktop}\s+")
active=$(xprop -root | grep '^_NET_ACTIVE_W' | awk -F'# 0x' '{print $2}')
apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1-3,5- | \
           grep ${active} | sed 's/[a-zA-Z0-9-]*\.//')
apps=$(echo -n "$apps" | sed -r "s/0x.*${active}(\s+)//")

# Add spaces to align the WM_NAMEs of the windows
max=$(echo -n "$apps" | awk '{cur=length($2); \
                              max=(cur>max?cur:max)} END{print max}')
wm=$(wmctrl -m | grep Name: | awk '{print $2}')

apps=$(echo -n "$apps" | \
           awk -v max="$max" \
               -v wm="$wm" \
               '{cur=length($2);
                 group[0]="one";
                 group[1]="two";
                 group[2]="three";
                 group[3]="four";
                 group[4]="five";
                 group[5]="six";
                 group[6]="seven";
                 group[7]="eight";
                 group[8]="nine";
                 if(wm=="CWM") $1-=1;
                 printf "%-8s", group[$1];
                 printf $2;
                 for(i=0;i<max-cur+1;i++) printf " ";
                 $1=$2="";
                 printf "%s\n", $0}')

opt=(
    -l $lines
    -i
    -p $title
)

cat <<EOF | dmenu ${opt[@]}
desktop - $(echo -n "$apps" | awk '{print $1}')
class   - $(echo -n "$apps" | awk '{print $2}')
title   - $(echo -n "$apps" | awk '{$1=$2=""; print $0}' | sed 's/^[ \t]*//')
EOF
