#!/bin/bash

# dmenu to use only desktop files

title="drun:"
lines=10
apppaths=(
    $HOME/.local/share/applications
    /usr/local/share/applications
    /usr/share/applications
)

desktops() {
    entries=$(ls ${apppaths[@]} | sort | uniq)
    for entry in $entries; do
        if [[ $entry == *.desktop ]]; then
            printf "%s\n" "${entry%.*}"
        fi
    done
}

launch() {
    app=$1
    for path in ${apppaths[@]}; do
        full="${path}/${app}.desktop"
        if [ -f "$full" ]; then
            exec $(awk -F= '/^Exec/ {print $2; exit}' $full | awk '{print $1}')
        fi
    done
}

case $1 in
    '' )
        app=$(desktops | dmenu -i -l $lines -p $title)
        launch $app
        ;;
    * )
        launch "$1"
        ;;
esac
