#!/bin/bash

title="tag:"
lines=10

tags=$(wmctrl -d 2>/dev/null | grep -v nogroup | tr -s '[:blank:]' | cut -d ' ' -f 1,2,9,10)
tags=$(echo -n "$tags" | \
          awk '{
                 if ($4 != "") {
                   printf "%-8s", $1; \
                   printf "%-4s", $2; \
                   printf "%-10s", $4; \
                 } else {
                   printf "%-8s", $3; \
                   printf "%-4s", $2; \
                 } \
                 printf "\n"; \
               }')

target=$(echo -n "$tags" | dmenu -l $lines -i -ix -p $title)

if [ -n "$target" ]; then
    xdotool key super+$(expr $target + 1)
fi
