#!/bin/bash

[ $# -lt 1 ] && cat <<EOF && exit
Usage: $(basename $0) {app} [cmd]
EOF

app=${1}
cmd=${2:-$app}
title="app:"
lines=10
windows=$(wmctrl -xl 2>/dev/null)
num=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 3 | \
          grep -i "^$app" | wc -l)

app_run() {
    hash $cmd 2>/dev/null
    if [ $? -eq 0 ]; then
        exec $cmd
    fi
}

app_menu() {
    apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 2-3,5- | \
               sed 's/[a-zA-Z0-9-]*\.//' | grep -i "$app" )
    # Add spaces to align the WM_NAMEs of the apps
    max=$(echo -n "$apps" | awk '{cur=length($2); \
                                  max=(cur>max?cur:max)} END{print max}')
    apps=$(echo -n "$apps" | \
               awk -v max="$max" \
                   '{cur=length($2); \
                     printf $2; \
                     for(i=0; i < max - cur + 1; i++) printf " "; \
                     if($1!="0") printf "%2s", $1; \
                     $1=$2=""; \
                     printf "%s\n", $0}')
    target=$(echo -n "$apps" | dmenu -l $lines -i -ix -r -p $title)
    case $target in
        '' ) exit ;;
        NEW )
            app_run
            ;;
        * )
            apps=($(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1,3 | \
                       grep -i "[[:space:]]\+$app" | cut -d ' ' -f 1))
            exec wmctrl -i -a ${apps[$target]}
            ;;
    esac
}

case $num in
    0 )
        app_run
        ;;
    * )
        app_menu
        ;;
esac
