#!/bin/bash

title="date:"
lines=10

mktime() {
    ZONE=$(date +'%Z')
    # If Sunday, show the week number of the next week
    if [ $(date +'%u') -gt 6 ]; then
        WEEK=$(date +'W%-V' -d "next Mon")
    else
        WEEK=$(date +'W%-V')
    fi
    TIME=$(date +'%a %-e %b %-l:%M %p %:::z %Y')
    echo "${ZONE} - ${WEEK} ${TIME}"
}

opt=(
    -l $lines
    -i
    -p $title
)

cat <<EOF | dmenu ${opt[@]}
$(TZ="Asia/Shanghai" mktime)
$(TZ="UTC" mktime)
$(TZ="America/Los_Angeles" mktime)
EOF
