#!/bin/bash

title="wincd:"
lines=10
desktop=$(xdotool get_desktop)
windows=$(wmctrl -xl 2>/dev/null | grep -E "\s+${desktop}\s+")
apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 2-3,5- | \
           sed 's/[a-zA-Z0-9-]*\.//')

# Add labels
labels=(one two three four five six seven eight nine)
wm=$(wmctrl -m | grep Name: | awk '{print $2}')
case $wm in
    CWM ) t=$(($desktop-1)) ;;
    * ) t=$desktop ;;
esac
l=${labels[$t]}
apps=$(echo -n "$apps" | sed -r "s/^${desktop}(\s+)/${l}\1/")

# Add spaces to align the WM_NAMEs of the windows
max=$(echo -n "$apps" | awk '{cur=length($2); \
                              max=(cur>max?cur:max)} END{print max}')

apps=$(echo -n "$apps" | \
           awk -v max="$max" \
               '{cur=length($2); \
                 printf "%-8s", $1; \
                 printf $2; \
                 for(i=0; i < max - cur + 1; i++) printf " "; \
                 $1=$2=""; \
                 printf "%s\n", $0}')

target=$(echo -n "$apps" | dmenu -l $lines -i -ix -p $title)

if [ -n "$target" ]; then
    apps=($(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1))
    winid=${apps[$target]}
    xdotool windowactivate $winid
    xdotool windowraise $winid
    xdotool windowfocus $winid
fi
