#!/bin/bash

title="operation:"
lines=10
menu=(
    "cancel"      # 0
    "logout"      # 1
    "reload"      # 2
    "shutdown"    # 3
    "reboot"      # 4
    "lock"        # 5
    "off-screen"  # 6
)

sudorun() {
    password=$(echo -n | dmenu -P -p "[sudo] password for $USER:")
    printf '%s\n' "$password" | sudo -S $*
}

choice=$(printf '%s\n' "${menu[@]}" | dmenu -i -ix -l $lines -p $title)
case $choice in
    0 ) exit ;;
    1 ) xdotool key super+shift+q ;;
    2 ) xdotool key super+shift+control+q ;;
    3 ) sudorun shutdown -h now ;;
    4 ) sudorun reboot ;;
    5 ) slock ;;
    6 ) xset dpms force off ;;
esac
