#!/bin/bash

title="window:"
lines=10
windows=$(wmctrl -xl 2>/dev/null)
apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 2-3,5- | \
           sed 's/[a-zA-Z0-9-]*\.//')

# Add labels
labels=(one two three four five six seven eight nine)
tags=$(wmctrl -d | grep -v nogroup | wc -l)
for((i=0; i<$tags; i++)); do
    case $DESKTOP_SESSION in
        cwm ) t=$(($i+1)) ;;
        * ) t=$i ;;
    esac
    l=${labels[$i]}
    s=" "
    apps=$(echo -n "$apps" | sed "s/^${t}\s\+/${l}${s}/")
done

# Add spaces to align the WM_NAMEs of the windows
max=$(echo -n "$apps" | awk '{cur=length($2); \
                              max=(cur>max?cur:max)} END{print max}')

apps=$(echo -n "$apps" | \
           awk -v max="$max" \
               '{cur=length($2); \
                 printf "%-8s", $1; \
                 printf $2; \
                 for(i=0; i < max - cur + 1; i++) printf " "; \
                 $1=$2=""; \
                 printf "%s\n", $0}')

target=$(echo -n "$apps" | dmenu -l $lines -i -ix -p $title)

if [ -n "$target" ]; then
    apps=($(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1))
    winid=${apps[$target]}
    xdotool windowactivate $winid
    xdotool windowraise $winid
    xdotool windowfocus $winid
fi
