#!/bin/bash

menupath=/usr/local/bin
app=$(basename $0)
title="menu:"
lines=10
ignores=(
    $app
    dmenu_path
)

menus=$(find $menupath/dmenu_* -maxdepth 1 -type f -executable 2>/dev/null \
            | sed 's|^'$menupath/'||' \
            | sort)

for ig in ${ignores[@]}; do
    menus=$(echo -n "$menus" | grep -v $ig)
done

target=$(echo -n "$menus" | dmenu -p $title -l $lines)
if [ -n "$target" ]; then
    exec $menupath/$target
fi
