#!/bin/bash

title="date:"
lines=10

mktime() {
    DESC=$1

    # If Sunday, show the week number of the next week
    if [ $(TZ="$TZ" date +'%u') -gt 6 ]; then
        WEEK=$(TZ="$TZ" date +'W%-V' -d "next Mon")
    else
        WEEK=$(TZ="$TZ" date +'W%-V')
    fi

    TIME=$(TZ="$TZ" date +'%a %-e %b %-l:%M %p %z %Z %Y')
    MAX=$(echo -n "${DESC}" | awk '{cur=length($1); \
                                    max=(cur>max?cur:max)} END{print max}')
    printf "%-${MAX}s - %s\n" "${DESC}" "${WEEK} ${TIME}"
}

opt=(
    -l $lines
    -i
    -p $title
)

# Stream the isolated cross-region time zones into dmenu mapping safely
cat <<EOF | dmenu ${opt[@]}
$(TZ="Asia/Shanghai" mktime "SH")
$(TZ="UTC" mktime "UT")
$(TZ="America/New_York" mktime "NY")
$(TZ="America/Los_Angeles" mktime "LA")
EOF
