#!/bin/bash

title="man:"
page=$(man -k . | sort \
                | awk '{ print $1 " " $2 }' \
                | dmenu -p $title -l 10 \
                | tr -d ' ')

if [ -n "$page" ]; then
    exec st -t "$title$page $$@$(hostname)" -e man "$page"
fi
