#!/bin/bash

title="info:"
lines=10
desktop=$(xdotool get_desktop)
windows=$(wmctrl -xl 2>/dev/null | grep -E "\s+${desktop}\s+")
active=$(xprop -root | grep '^_NET_ACTIVE_W' | awk -F'# 0x' '{print $2}')
apps=$(echo -n "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1-3,5- | \
           grep ${active} | sed 's/[a-zA-Z0-9-]*\.//')
apps=$(echo -n "$apps" | sed -r "s/0x.*${active}(\s+)//")

# Add labels
labels=(one two three four five six seven eight nine)
wm=$(wmctrl -m | grep Name: | awk '{print $2}')
case $wm in
    CWM ) t=$(($desktop-1)) ;;
    * ) t=$desktop ;;
esac
l=${labels[$t]}
apps=$(echo -n "$apps" | sed -r "s/^${desktop}(\s+)/${l}\1/")

# Add spaces to align the WM_NAMEs of the windows
max=$(echo -n "$apps" | awk '{cur=length($2); \
                              max=(cur>max?cur:max)} END{print max}')

apps=$(echo -n "$apps" | \
           awk -v max="$max" \
               '{cur=length($2);
                 printf "%-8s", $1;
                 printf $2;
                 for(i=0;i<max-cur+1;i++) printf " ";
                 $1=$2="";
                 printf "%s\n", $0}')
echo -n "$apps" | dmenu -l $lines -i -ix -p $title
