#!/bin/bash

title="man:"
lines=10
page=$(man -k . | sort \
                | awk '{ print $1 " " $2 }' \
                | dmenu -p $title -l $lines \
                | tr -d ' ')

if [ -n "$page" ]; then
    exec st -t "$title$page $$@$(hostname)" -e man "$page"
fi
