#!/bin/bash

title="desktop:"
lines=10

desks() {
    labels=(one two three four five six seven eight nine)
    tags=$(wmctrl -d | grep -v nogroup | wc -l)
    group=$(xdotool get_desktop)
    total=$(wmctrl -l | awk '{print $2}' | wc -l)
    for((i=0; i<$tags; i++)); do
        label="${labels[$i]}"
        case $DESKTOP_SESSION in
            cwm ) g=$(expr $i + 1) ;;
            * ) g=$i ;;
        esac
        num=$(wmctrl -l | awk '{print $2}' | grep -sc "^${g}$")
        if [ ${group} -eq ${g} ]; then
            flag1="*"
        else
            flag1="-"
        fi
        if [ ${num} -ne 0 ]; then
            flag2="+"
        else
            flag2="="
        fi
        status="${num}/${total}"
        printf '%-10s%5s%10s%20s\n' \
               "${label}" "${flag1}" "${flag2}" "${status}"
    done
}

target=$(desks | dmenu -l $lines -i -ix -p $title)
if [ -n "$target" ]; then
    case $DESKTOP_SESSION in
        dwm ) xdotool key super+$(expr $target + 1) ;;
        cwm ) wmctrl -s $(expr $target + 1) ;;
        * ) wmctrl -s $target ;;
    esac
fi
