#!/bin/bash

menupath=/usr/local/bin
app=$(basename $0)
title="menu:"
ignores=(
    $app
    dmenu_path
)

menus=$(find $menupath/dmenu_* -maxdepth 1 -type f -executable \
            | sed 's|^'$menupath/'||' \
            | sort)

for ig in ${ignores[@]}; do
    menus=$(echo "$menus" | grep -v $ig)
done

target=$(echo "$menus" | dmenu -p $title -l 10)
if [ -n "$target" ]; then
    exec $menupath/$target
fi
