#!/bin/sh

STATUS_FIFO="/tmp/dvtm-status.fifo"
CMD_FIFO="/tmp/dvtm-command.fifo"

[ -p "$STATUS_FIFO" ] || mkfifo -m 600 "$STATUS_FIFO" || exit 1
[ -p "$CMD_FIFO" ] || mkfifo -m 600 "$CMD_FIFO" || exit 1

cleanup() {
    kill "$STATUS_PID" 2>/dev/null
    wait "$STATUS_PID" 2>/dev/null
    rm -f "$STATUS_FIFO" "$CMD_FIFO"
}
trap cleanup 0 1 15

mktime() {
    # If Sunday, show the week number of the next week
    if [ $(date +'%u') -gt 6 ]; then
        WEEK=$(date +'W%-V' -d "next monday")
    else
        WEEK=$(date +'W%-V')
    fi
    TIME=$(date +'%a %-e %b %-l:%M %p')
    echo ${WEEK} ${TIME}
}

display() {
    echo "$(TZ=Asia/Shanghai mktime)"
}

while true; do
    display
    sleep 20
done > "$STATUS_FIFO" &
STATUS_PID=$!

dvtm -s "$STATUS_FIFO" -c "$CMD_FIFO" "$@" 2> /dev/null
EXIT_STATUS=$?

exit $EXIT_STATUS
