#!/bin/sh

cmd=emacsclient
if which $cmd > /dev/null 2>&1; then
    if [ -z "$DISPLAY" ]; then
        opt="-t"
    else
        opt="-c"
    fi
    $cmd -n "$opt" "$@" 2>/dev/null || echo "No emacs daemon."
else
    echo "$cmd not found!"
fi
