#!/bin/bash

# dmenu to use only desktop files

apppaths=(
    /usr/share/applications/
    /usr/local/share/applications/
)
entries=$(ls ${apppaths[@]})
desktops() {
    for entry in $entries; do
        if [[ $entry == *.desktop ]]; then
            echo "${entry%.*}"
        fi
    done
}
desktops | dmenu -i -l 10 -p drun "$@" | ${SHELL:-"/bin/sh"} &
