#!/bin/bash
apppaths=(
    /usr/share/applications/
    /usr/local/share/applications/
)
entries=$(ls ${apppaths[@]})
for entry in $entries; do
    if [[ $entry == *.desktop ]]; then
        echo "${entry%.*}"
    fi
done
