#!/bin/sh

HOST=$(hostname)
TITLE="man:"
PAGE=$(man -k . | sort \
                | awk '{ print $1 " " $2 }' \
                | dmenu -p $TITLE -l 10 \
                | tr -d ' ')

if [ -n "$PAGE" ]; then
  st -t "st:$PAGE $$@$HOST" -e man "$PAGE"
fi
