#!/bin/sh

# dmenu_run improved
# command ending with '!', is started in the terminal.

cmd="$(dmenu_path | dmenu -i -l 10 -p run "$@")"

case $cmd in
    '')  ;;
    *\!) exec "${TERMINAL:-st}" -e bash -c "${cmd%?}; read" ;;
    *)   exec ${cmd} ;;
esac
