#!/bin/sh

TERM_CMD=${TERM_CMD:-"st -t"}
MANPAGE="$(man -k . | sort \
                    | awk '{ print $1 " " $2 }' \
                    | dmenu -p 'Man:' -l 8 \
                    | tr -d ' ')"

if [ -n "$MANPAGE" ]; then
  $TERM_CMD "$MANPAGE" -e man "$MANPAGE"
fi
