#!/bin/bash

if [[ -z $1 ]]; then
    cat <<EOF
Usage:
$(basename $0) {app}
EOF
    exit 1
fi

app=${1}
num=$(pgrep -f "^${app}$" | wc -l)

app_focus() {
    app_pid="$(pgrep -f "^${app}$")"
    wid=$(wmctrl -lp | grep "$app_pid" | awk '{print $1}')
    exec wmctrl -iR "$wid"
}

app_run() {
    hash $app 2> /dev/null
    if [ $? -eq 0 ]; then
        exec $app
    else
        echo "No $app can been found!"
    fi
}

app_menu() {
    windows=$(wmctrl -xl 2>/dev/null)
    apps=$(echo "$windows" | grep -i $app | tr -s '[:blank:]' |  cut -d ' ' -f 3-3,5- | \
               sed 's/^[a-zA-Z0-9-]*\.//' | sort | uniq)
    # Add spaces to align the WM_NAMEs of the apps
    max=$(echo "$apps" | awk '{cur=length($1); \
                               max=(cur>max?cur:max)} END{print max}')
    apps=$(echo "$apps" | \
               awk -v max="$max" \
                   '{cur=length($1); printf $1; \
                     for(i=0; i < max - cur + 1; i++) printf " "; \
                     $1 = ""; printf "%s\n", $0}')
    target=$(echo "$apps" | dmenu -l 10 -i -p app | \
                 tr -s '[:blank:]' | cut -d ' ' -f 2-)
    if [[ -n $target ]]; then
        exec wmctrl -a "$target"
    fi
}

case $num in
    1 )
        app_focus
        ;;
    0 )
        app_run
        ;;
    * )
        app_menu
        ;;
esac
