#!/bin/bash

[[ $# -lt 1 ]] && cat <<EOF && exit
Usage: $(basename $0) {app} [cmd]
EOF

app=${1}
cmd=${2:-$app}
title="app:"
windows=$(wmctrl -xl 2>/dev/null)
num=$(echo "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 3 | \
          grep -i "^$app" | wc -l)

app_run() {
    hash $cmd 2>/dev/null
    if [[ $? -eq 0 ]]; then
        exec $cmd
    else
        echo "No $cmd can been found!"
    fi
}

app_menu() {
    apps=$(echo "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 3-3,5- | \
               grep -i "^$app" | sed 's/^[a-zA-Z0-9-]*\.//')
    # Add spaces to align the WM_NAMEs of the apps
    max=$(echo "$apps" | awk '{cur=length($1); \
                               max=(cur>max?cur:max)} END{print max}')
    apps=$(echo "$apps" | \
               awk -v max="$max" \
                   '{cur=length($1); printf $1; \
                     for(i=0; i < max - cur + 1; i++) printf " "; \
                     $1 = ""; printf "%s\n", $0}')
    target=$(echo -e "New\n$apps" | dmenu -l 10 -i -ix -p $title)
    case $target in
        0 )
            app_run
            ;;
        * )
            apps=$(echo "$windows" | tr -s '[:blank:]' | cut -d ' ' -f 1,3 | \
                       grep -i "[[:space:]]\+$app" | cut -d ' ' -f 1)
            id=$(echo $apps | tr -s '[:blank:]' | cut -d ' ' -f $target)
            exec wmctrl -i -a $id
            ;;
    esac
}

case $num in
    0 )
        app_run
        ;;
    * )
        app_menu
        ;;
esac
