#!/bin/bash

title="ssh:"
term_cmd=${TERM_CMD:-"st -e"}
ssh_cmd=${SSH_CMD:-"ssh -t"}
remote_cmd=${REMOTE_CMD}

ssh_config=${SSH_CONFIG_FILE:-$HOME/.ssh/config}
ssh_hosts=( $(grep "^Host\s\+[^*]" $ssh_config 2>/dev/null | grep -v 'git.*com' | cut -d " " -f 2-) )
ssh_host=$(printf '%s\n' "${ssh_hosts[@]}" | sed -Ez '$ s/\n+$//' | dmenu -i -l 10 -p $title "$@")

if [ -n "$ssh_host" ]; then
    ssh $ssh_host hash mosh-server 2>/dev/null
    if [ $? -eq 0 ]; then
        ssh_cmd="mosh"
    fi
    exec $term_cmd $ssh_cmd $ssh_host $remote_cmd
fi
