#!/bin/bash

# dmenu to use only desktop files

apppaths=(
    $HOME/.local/share/applications/
    /usr/local/share/applications/
    /usr/share/applications/
)

desktops() {
    entries=$(ls ${apppaths[@]} | sort | uniq)
    for entry in $entries; do
        if [[ $entry == *.desktop ]]; then
            echo "${entry%.*}"
        fi
    done
}

app=$(desktops | dmenu -i -l 10 -p drun "$@")
exec gtk-launch $app
