#!/bin/bash

title="ssh:"
term_cmd=${TERM_CMD:-"st -e"}
ssh_cmd=${SSH_CMD:-"ssh -t"}
remote_cmd=${REMOTE_CMD}

config=${SSH_CONFIG_FILE:-$HOME/.ssh/config}
hosts=( $(grep "^Host\s\+[^*]" $config 2>/dev/null | grep -v 'git' | cut -d " " -f 2-) )
target=$(printf '%s\n' "${hosts[@]}" | sed -Ez '$ s/\n+$//' | dmenu -i -l 10 -p $title "$@")

if [ -n "$target" ]; then
    ssh $target hash mosh-server 2>/dev/null
    if [ $? -eq 0 ]; then
        ssh_cmd="mosh"
    fi
    exec $term_cmd $ssh_cmd $target $remote_cmd
fi
