name: Alpine CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: alpine

    steps:
    - uses: actions/checkout@v4
    - name: Install dependence
      run: apk add ncurses-dev make
    - name: Build dvtm
      run: make -C tools/dvtm LDFLAGS=-static
