name: Alpine CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/linuxcontainers/alpine:3.20

    steps:
    - uses: actions/checkout@v4
    - name: Install dependence
      run: apk add make gcc musl-dev ncurses-dev ncurses-static libbsd-static libbsd-dev
    - name: Build abduco
      run: make -C tools/abduco LDFLAGS=-static
    - name: Build dvtm
      run: make -C tools/dvtm LDFLAGS=-static
    - name: Build mtm
      run: make -C tools/mtm LDFLAGS=-static HEADERS='-DNCURSESW_INCLUDE_H="<ncurses.h>"'
    - name: Build MicroEMACS
      run: make -C tools/MicroEMACS LDFLAGS=-static
