name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dwm dependence
      run: sudo apt-get install -y libx11-dev libxft-dev libxinerama-dev
    - name: Install dwmstatus dependence
      run: sudo apt-get install -y libasound2-dev
    - name: Install xbanish dependence
      run: sudo apt-get install -y libxfixes-dev libxi-dev libxext-dev
    - name: Install slock dependence
      run: sudo apt-get install -y libxrandr-dev
    - name: Build dwm
      run: make -C src/
    - name: Build dmenu
      run: make -C tools/dmenu
    - name: Build dwmstatus
      run: make -C tools/dwmstatus
    - name: Build tabbed
      run: make -C tools/tabbed
    - name: Build xbanish
      run: make -C tools/xbanish
    - name: Build slock
      run: make -C tools/slock
