name: Ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install prepare
      run: apt-get update
    - name: Install build tools
      run: apt-get install -y gcc g++ make
    - name: Install dwm dependence
      run: apt-get install -y libx11-dev libxft-dev libxinerama-dev libxrender-dev
    - name: Install dwmstatus dependence
      run: apt-get install -y libasound2-dev
    - name: Install xbanish dependence
      run: apt-get install -y libxfixes-dev libxi-dev libxext-dev
    - name: Install slock dependence
      run: apt-get install -y libxrandr-dev
    - name: Install surf dependence
      run: apt-get install -y libwebkit2gtk-4.0-dev libgcr-3-dev
    - name: Install xcompmgr dependence
      run: apt-get install -y libxcomposite-dev libxdamage-dev
    - name: Build dwm
      run: make -C src/dwm
    - name: Build cwm
      run: make -C src/cwm
    - name: Build dmenu
      run: make -C tools/dmenu
    - name: Build dwmstatus
      run: make -C tools/dwmstatus
    - name: Build tabbed
      run: make -C tools/tabbed
    - name: Build xbanish
      run: make -C tools/xbanish
    - name: Build slock
      run: make -C tools/slock
    - name: Build shotkey
      run: make -C tools/shotkey
    - name: Build surf
      run: make -C tools/surf
    - name: Build xcompmgr
      run: make -C tools/xcompmgr
    - name: Build utils
      run: make -C tools/utils
